rearrange configuration
* moved fakesensor config to boards in nuttx
* renamed config keys
* added dependencies for mocking program
* used code from romfs example for generating romfs on build
* updated romfs dev mount style to be like romfs example

diff --git a/mocking/Makefile b/mocking/Makefile
--- a/mocking/Makefile
+++ b/mocking/Makefile
@@ -13,4 +13,25 @@ MODULE    = $(CONFIG_INSPACE_MOCKING)
 
 MAINSRC = mocking_main.c
 
+# Common build
+
+checkgenromfs:
+	@genromfs -h 1>/dev/null 2>&1 || { \
+ echo "Host executable genromfs not available in PATH"; \
+ echo "You may need to download in from http://romfs.sourceforge.net/"; \
+ exit 1; \
+	}
+
+data.img: checkgenromfs
+	@genromfs -f $@ -d test-data -V "mocking-romfs" || { echo "genromfs failed" ; exit 1 ; }
+
+data_romfs.h: data.img
+	@xxd -i $< >$@ || { echo "xxd of $< failed" ; exit 1 ; }
+
+context:: data_romfs.h
+
+distclean::
+	$(call DELFILE, data.img)
+	$(call DELFILE, data.img.h)
+
 include $(APPDIR)/Application.mk
